### ISSUE TITLE
Email not being sent to hotmail?

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Infrastructure#1]
Not in spam

**Comment by jvyden** [comment]
It seems Microsoft has us (or Vultr's IP range) on their blocklist:

```
This is the mail system at host mail.jvyden.xyz.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<xxxxx@hotmail.com>: host
    hotmail-com.olc.protection.outlook.com[104.47.1.33] said: 550 5.7.1
    Unfortunately, messages from [45.77.207.115] weren't sent. Please contact
    your Internet service provider since part of their network is on our block
    list (S3150). You can also refer your provider to
    http://mail.live.com/mail/troubleshooting.aspx#errors.
```

I signed up for their Junk Mail Reporting Program, and SNDS thing, so we'll see how things go out from here.

**Comment by jvyden** [comment]
Nope, still can't send mail to Outlook. Let me see if I can get our mail server whitelisted.

**Comment by jvyden** [comment]
Sent in a request through some form I found while googling the error code S3150, no idea when I can expect a response. There's not too many people that have tried to send verification requests to outlook addresses, so I guess it's not too much of a problem for now. /shrug

**Comment by speedyman08** [comment]
what did you do to get your domain blacklisted from outlook

**Comment by jvyden** [comment]
Noticed Microsoft started sending me DMARC reports today. Did some deliverability tests and everything now seems to be in order. No idea what happened, but hopefully things should be smooth with Outlook now.
